version: '3'
tasks:
  test:
    cmd: 'docker compose exec rector-php sh -c "vendor/bin/phpunit --coverage-html var/coverage"'

  cs-fix:
    cmd: 'docker compose exec rector-php sh -c "vendor/bin/php-cs-fixer fix --diff --verbose {{.CLI_ARGS}}"'

  cs:
    cmds:
      - task: cs-fix
        vars:
          CLI_ARGS: "--dry-run --stop-on-violation {{.CLI_ARGS}}"

  run:
    cmds:
      - task: rector
        vars:
          CLI_ARGS: "--config=/Users/mikhailsavin/projects/AddNamedArgumentsRector/rector.dev.php {{.CLI_ARGS}}"

  rector-fix:
    cmd: 'vendor/bin/rector process {{.CLI_ARGS}}'

  rector:
    cmds:
      - task: rector-fix
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  stan:
    cmd: 'docker compose exec rector-php sh -c "vendor/bin/phpstan {{.CLI_ARGS}}"'

  install:
    cmd: 'docker compose exec rector-php sh -c "composer install"'
    sources:
      - composer.json
      - composer.lock
    generates:
      - vendor/autoload.php

  composer-normalize-fix:
    deps: [install]
    cmds:
      - 'composer normalize --diff {{.CLI_ARGS}}'

  composer-normalize:
    cmds:
      - task: composer-normalize-fix
        vars:
          CLI_ARGS: '--dry-run {{.CLI_ARGS}}'

  composer-validate: 'composer validate --strict --no-check-publish {{.CLI_ARGS}}'

  composer-audit: 'composer audit {{.CLI_ARGS}}'

  composer-check-require:
    deps: [install]
    cmd: 'vendor/bin/composer-require-checker check {{.CLI_ARGS}}'

  composer-check-unused:
    deps: [install]
    cmd: 'vendor/bin/composer-unused {{.CLI_ARGS}}'

  check:
    cmds:
      - task: cs
#      - task: stan
      - task: rector
      - task: test
      - task: composer-validate
      - task: composer-audit
      - task: composer-normalize
#      - task: composer-check-require
#      - task: composer-check-unused
